# Generated by Django 4.2.16 on 2025-05-22 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('community', '0003_alter_comment_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='movie_title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='core.movie'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='core.genre'),
        ),
    ]
