# Generated by Django 4.2.16 on 2025-05-23 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('community', '0004_article_movie_title_alter_article_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='genre',
        ),
        migrations.AddField(
            model_name='article',
            name='genre',
            field=models.ManyToManyField(related_name='articles', to='core.genre'),
        ),
    ]
