# Generated by Django 4.2.16 on 2025-05-22 02:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergenrepreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genre_preferences', to=settings.AUTH_USER_MODEL),
        ),
    ]
