# Generated by Django 4.2.16 on 2025-05-22 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('accounts', '0004_alter_usergenrepreference_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='preferred_genres',
            field=models.ManyToManyField(blank=True, related_name='user_genre', through='accounts.UserGenrePreference', to='core.genre'),
        ),
        migrations.AlterField(
            model_name='usergenrepreference',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.genre'),
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
