# Generated by Django 4.2.16 on 2025-05-26 03:55

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_watchhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='default_profile.jpg', null=True, upload_to=accounts.models.user_profile_image_path),
        ),
    ]
