# Generated by Django 4.2.16 on 2025-05-26 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_profile_image'),
        ('accounts', '0007_favoritemovie'),
    ]

    operations = [
    ]
