# Generated by Django 4.2.16 on 2025-05-27 20:16

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_merge_20250526_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(default='default_profile.jpg', upload_to=accounts.models.user_profile_image_path),
        ),
    ]
